changelog:
  categories:
    - title: ğŸš€ Features
      labels: [feature, enhancement]
      collapse-after: 10
    - title: ğŸ› Bug Fixes
      labels: [bug, fix]
    - title: ğŸ“¦ Other Changes
      labels: [chore, docs, refactor, test]
  exclude:
    labels:
      - ignore-for-release